// Copyright (c) 2025 LG Electronics, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

use actix_web::{App, HttpServer, middleware, web};
use migrator::setup_tables::setup_tables;
use scmscommon::{AppState, load_global_config, load_mysql_config, setup_db};
use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;
use utoipauto::utoipauto;
mod core_logic;
mod core_types;
mod endpoint;
mod errors;
mod load_aca_certificates_keys;
mod migrator;
mod persistence;
mod test_helper;

#[allow(unused_imports)] // Disables all warnings for entities (generated by sea-orm)
mod entities;

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    env_logger::init_from_env(env_logger::Env::new().default_filter_or("info"));

    // Load the configuration objects we are interested in
    let global_config = load_global_config();
    load_mysql_config();

    let app_state = web::Data::new(AppState {
        app_name: "ACA server".to_string(),
        db: setup_db().await.unwrap(),
        celery_app: None,
    });

    // Setup database access
    setup_tables(&app_state.db).await.unwrap();

    // Load Aca Certificates
    load_aca_certificates_keys::load_certificates_to_database(&app_state.db)
        .await
        .unwrap();

    #[utoipauto(paths = "./aca/src,./scmscommon/src from scmscommon")]
    #[derive(OpenApi)]
    #[openapi(info(title = "Authorization Certificate Authority (ACA)"))]
    struct OpenApiDoc;
    let openapi = OpenApiDoc::openapi();

    HttpServer::new(move || {
        App::new()
            .wrap(middleware::Logger::default())
            .app_data(app_state.clone())
            .service(endpoint::healthcheck)
            .service(endpoint::process_ra_request)
            .service(endpoint::get_plvs_using_ls)
            .service(
                SwaggerUi::new("/swagger-ui/{_:.*}").url("/api-docs/openapi.json", openapi.clone()),
            )
    })
    .bind(("0.0.0.0", global_config.aca_port))
    .unwrap()
    .run()
    .await
}
