// Copyright (c) 2025 LG Electronics, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Disable type complexity for this component
#![allow(clippy::type_complexity)]
#![allow(non_local_definitions)] //For celery macros
#![allow(clippy::enum_variant_names)]

use actix_web::{App, HttpResponse, HttpServer, Responder, middleware, web};
use celery::beat::CronSchedule;
use derive_more::Display;
use migrator::setup_tables::setup_tables;
use scmscommon::{AppState, GlobalConfig, errors, load_global_config, load_mysql_config, setup_db};
use sea_orm::DatabaseConnection;
use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;
use utoipauto::utoipauto;

mod core_logic;
mod load_ra_certificates_keys;
mod migrator;
mod persistence;
mod ra_endpoint;
mod raconfig;
mod test_helper;

#[allow(unused_imports)] // Disables all warnings for entities (generated by sea-orm)
mod entities;

use crate::ra_endpoint::worker::tasks::{
    eca_public_key_download_and_store, run_authorization_request_processing,
    run_periodic_eca_public_key_download, run_successor_enrollment_request,
};

#[derive(Debug, Display)]
enum RaMode {
    FrontEnd,
    Worker,
}

fn get_mode() -> RaMode {
    let args: Vec<String> = std::env::args().collect();

    if args.len() > 1 {
        match args[1].to_lowercase().as_str() {
            "frontend" => RaMode::FrontEnd,
            "worker" => RaMode::Worker,
            _ => panic!(
                "Invalid operation mode for RA. Specify either Frontend or Worker (case insensitive)"
            ),
        }
    } else {
        RaMode::FrontEnd
    }
}

/// Provide a health-check endpoint for the service
///
/// Simply responds with an HTTP Status of 200
#[utoipa::path(
    get,
    tag = "Service",
    path = "/healthcheck",
    responses((status = 200, description = "Success", body = String))
)]
#[actix_web::get("/healthcheck")]
async fn healthcheck(data: web::Data<AppState>) -> impl Responder {
    let server_name = data.app_name.clone();
    HttpResponse::Ok().body(format!("{server_name} is healthy\n"))
}

async fn load_eca_public_key_and_setup_periodic_task(
    db: &DatabaseConnection,
    ra_config: &raconfig::RaConfig,
) -> Result<(), errors::ScmsInternalCommError> {
    // Lets try to Download ECA public key first time
    // if it's fail for some reason, RA will try later
    let result = eca_public_key_download_and_store(db).await;
    if let Err(e) = result {
        log::warn!("Failed to download ECA public key first time: {:#?}", e);
    }

    // Setup and trigger scheduled task to update weekly the eca public key
    let _ = celery::beat!(
        broker = AMQPBroker {ra_config.rabbitmq_connection_string.clone()},
        tasks = [
            "run_periodic_eca_public_key_download" => {
                run_periodic_eca_public_key_download,
                schedule = CronSchedule::from_string("0 0 * * 0")?,
                args = ()
            },
        ],
        task_routes = [],
    )
    .await
    .map_err(|e| {
        errors::ScmsInternalCommError::new(
            &format!("Failed to create celery beat: {}", e),
            errors::InternalCommWire::EcaToRa,
            500,
        )
    })?;

    log::debug!("Downloaded and stored eca public key.");
    Ok(())
}

#[actix_web::main]
async fn main() -> () {
    // Common initialization for both instances
    env_logger::init_from_env(env_logger::Env::new().default_filter_or("info"));

    // Load the configuration objects we are interested in
    let global_config = load_global_config();
    log::debug!("{:#?}", global_config);
    load_mysql_config();
    let ra_config = raconfig::load_ra_config();

    let my_app = celery::app!(
        broker = AMQPBroker {ra_config.rabbitmq_connection_string.clone()},
        tasks = [run_authorization_request_processing, run_successor_enrollment_request],task_routes=[]
    )
    .await
    .expect("Failed to create celery app");

    let app_state = web::Data::new(AppState {
        app_name: "RA server".to_string(),
        db: setup_db().await.unwrap(),
        celery_app: Some(my_app.clone()),
    });

    match get_mode() {
        RaMode::FrontEnd => {
            log::info!("Launching RA Frontend service");

            // Setup database access
            setup_tables(&app_state.clone().db).await.unwrap();

            // Loading ECA public key
            // TODO: that should be done by only one RA-front end instance
            match load_eca_public_key_and_setup_periodic_task(&app_state.clone().db, ra_config)
                .await
            {
                Ok(_) => log::debug!("ECA public key loaded and periodic task setup"),
                Err(e) => log::warn!("Failed to load ECA public key first time: {:#?}", e),
            }

            load_ra_certificates_keys::load_certificates_to_database(&app_state.clone().db)
                .await
                .expect("Failed to load RA certificates and keys to database");

            load_ra_certificates_keys::build_load_crl_ccf_ctl_to_ra_db(&app_state.clone().db)
                .await
                .expect("Failed to build and load CRL, CCF and CTL to RA database");

            #[utoipauto(paths = "./ra/src,./scmscommon/src from scmscommon")]
            #[derive(OpenApi)]
            #[openapi(info(title = "Registration Authority (RA)"))]
            struct OpenApiDoc;

            let openapi = OpenApiDoc::openapi();
            let _ = HttpServer::new(move || {
                App::new()
                    .wrap(middleware::Logger::default())
                    .app_data(app_state.clone())
                    .service(healthcheck)
                    .service(
                        web::scope("/v3")
                            .service(ra_endpoint::request_auth_certificate)
                            .service(ra_endpoint::download_auth_certificate)
                            .service(ra_endpoint::request_successor_enrollment_certificate)
                            .service(ra_endpoint::download_successor_certificate)
                            .service(ra_endpoint::download_ra_certificate)
                            .service(ra_endpoint::download_ca_certificate)
                            .service(ra_endpoint::download_certificate_trust_list)
                            .service(ra_endpoint::download_certificate_chain_file)
                            .service(ra_endpoint::certificate_management_info_status_download)
                            .service(ra_endpoint::individual_crl_download)
                            .service(ra_endpoint::composite_crl_ctl),
                    )
                    .service(ra_endpoint::handle_ee_registration)
                    .service(ra_endpoint::handle_get_ee)
                    .service(ra_endpoint::handle_patch_ee)
                    .service(ra_endpoint::handle_get_policy)
                    .service(
                        SwaggerUi::new("/swagger-ui/{_:.*}")
                            .url("/api-docs/openapi.json", openapi.clone()),
                    )
            })
            .bind(("0.0.0.0", GlobalConfig::global().ra_port))
            .unwrap()
            .run()
            .await;
        }
        RaMode::Worker => {
            log::info!("Launching RA Worker service");
            let _ = my_app.consume().await;
        }
    }

    let _ = my_app.close().await;
}
