// Copyright (c) 2025 LG Electronics, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "caterpillar_status")]
pub enum CaterpillarStatus {
    #[sea_orm(string_value = "ToBeProcessed")]
    ToBeProcessed,
    #[sea_orm(string_value = "Processing")]
    Processing,
    #[sea_orm(string_value = "Processed")]
    Processed,
    #[sea_orm(string_value = "Queued")]
    Queued,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "device_type")]
pub enum DeviceType {
    #[sea_orm(string_value = "OBU")]
    Obu,
    #[sea_orm(string_value = "RSU")]
    Rsu,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "enrollment_status")]
pub enum EnrollmentStatus {
    #[sea_orm(string_value = "ToBeProcessed")]
    ToBeProcessed,
    #[sea_orm(string_value = "Processing")]
    Processing,
    #[sea_orm(string_value = "Processed")]
    Processed,
    #[sea_orm(string_value = "Downloaded")]
    Downloaded,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "exp_type")]
pub enum ExpType {
    #[sea_orm(string_value = "Obk")]
    Obk,
    #[sea_orm(string_value = "Ubk")]
    Ubk,
    #[sea_orm(string_value = "Cubk")]
    Cubk,
    #[sea_orm(string_value = "ObkAcpc")]
    ObkAcpc,
    #[sea_orm(string_value = "UbkAcpc")]
    UbkAcpc,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "ra_request_management_request_type"
)]
pub enum RaRequestManagementRequestType {
    #[sea_orm(string_value = "SuccessorEnrollmentRequest")]
    SuccessorEnrollmentRequest,
    #[sea_orm(string_value = "SuccessorEnrollmentDownload")]
    SuccessorEnrollmentDownload,
    #[sea_orm(string_value = "AuthorizationRequest")]
    AuthorizationRequest,
    #[sea_orm(string_value = "AuthorizationDownload")]
    AuthorizationDownload,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "Registered")]
    Registered,
    #[sea_orm(string_value = "Enrolled")]
    Enrolled,
    #[sea_orm(string_value = "Successor-Enrolled")]
    SuccessorEnrolled,
    #[sea_orm(string_value = "Blocked")]
    Blocked,
    #[sea_orm(string_value = "Provisioning")]
    Provisioning,
    #[sea_orm(string_value = "Deleted")]
    Deleted,
}
